spring.application.name=ticketflow
spring.datasource.url=jdbc:postgresql://localhost/ticketflow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1193

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:1193}